export enum Type {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE',
}

export enum Language {
  EN = 'EN',
  HE = 'HE',
}

export enum Category {
  APARTMENT_RENT = 'APARTMENT_RENT',
  PROPERTY_TAX = 'PROPERTY_TAX',
  HOUSE_COMMITTEE = 'HOUSE_COMMITTEE',
  MEDICAL_INSURANCE = 'MEDICAL_INSURANCE',
  TRANSPORTATION = 'TRANSPORTATION',
  SCOOTER = 'SCOOTER',
  HOUSE_INSURANCE = 'HOUSE_INSURANCE',
  SUPERMARKET = 'SUPERMARKET',
  PHARMA = 'PHARMA',
  TAKEAWAY_RESTAURANT = 'TAKEAWAY_RESTAURANT',
  RESTAURANT = 'RESTAURANT',
  BAR = 'BAR',
  ELECTRICITY_BILL = 'ELECTRICITY_BILL',
  GAS_BILL = 'GAS_BILL',
  WATER_BILL = 'WATER_BILL',
  PHONE_BILL = 'PHONE_BILL',
  INTERNET_BILL = 'INTERNET_BILL',
  TELEVISION_BILL = 'TELEVISION_BILL',
  FINE = 'FINE',
  ADVICE_SERVICE = 'ADVICE_SERVICE',
  CAR_CARE = 'CAR_CARE',
  CAR_INSURANCE_BASIC = 'CAR_INSURANCE_BASIC',
  CAR_INSURANCE_EXTRA = 'CAR_INSURANCE_EXTRA',
  CAR_TEST = 'CAR_TEST',
  PARKING_BILL = 'PARKING_BILL',
  FUEL = 'FUEL',
  INTERNET_MEMBERSHIP = 'INTERNET_MEMBERSHIP',
  SPORT_MEMBERSHIP = 'SPORT_MEMBERSHIP',
  MEMBERSHIP = 'MEMBERSHIP',
  SPORT_TICKET = 'SPORT_TICKET',
  CONCERT_TICKET = 'CONCERT_TICKET',
  VACATION_IN_HOUSE = 'VACATION_IN_HOUSE',
  VACATION_ON_BOARD = 'VACATION_ON_BOARD',
  CLOTHE = 'CLOTHE',
  ELECTRONIC_GADGET = 'ELECTRONIC_GADGET',
  GIFT = 'GIFT',
  ADVANCED_STUDY_FUND = 'ADVANCED_STUDY_FUND',
  PROVIDENT_FUND = 'PROVIDENT_FUND',
  PENSION_FUND = 'PENSION_FUND',
  OTHER = 'OTHER',
}

export enum ExpenseType {
  INCIDENTAL = 'INCIDENTAL',
  FIXED = 'FIXED',
}
