import { Category, Type } from './dto/enums';

export const categoriesTitleMapping = new Map<Category, string>([
  [Category.APARTMENT_RENT, 'Apartment Rent'],
  [Category.ADVANCED_STUDY_FUND, 'Advanced Study Fund'],
  [Category.ADVICE_SERVICE, 'Advice Service'],
  [Category.BAR, 'Bar'],
  [Category.CAR_CARE, 'Car Care'],
  [Category.CAR_TEST, 'Car Test'],
  [Category.CAR_INSURANCE_BASIC, 'Car Insurance Basic'],
  [Category.CAR_INSURANCE_EXTRA, 'Car Insurance Extra'],
  [Category.CONCERT_TICKET, 'Concert Ticket'],
  [Category.CLOTHING, 'Clothing'],
  [Category.ELECTRICITY_BILL, 'Electricity Bill'],
  [Category.ELECTRONIC_GADGET, 'Electric Gadget'],
  [Category.FINE, 'Fine'],
  [Category.FUEL, 'Fuel'],
  [Category.GAS_BILL, 'Gas Bill'],
  [Category.GIFT, 'Gift'],
  [Category.HOUSE_COMMITTEE, 'House Committee'],
  [Category.HOUSE_INSURANCE, 'House Insurance'],
  [Category.INTERNET_BILL, 'Internet Bill'],
  [Category.INTERNET_MEMBERSHIP, 'Internet Membership'],
  [Category.MEDICAL_INSURANCE, 'Medical Insurance'],
  [Category.MEMBERSHIP, 'Membership'],
  [Category.OTHER, 'Other'],
  [Category.PHONE_BILL, 'Phone Bill'],
  [Category.PARKING_BILL, 'Parking Bill'],
  [Category.PENSION_FUND, 'Pension Fund'],
  [Category.PHARMA, 'Pharma'],
  [Category.PROPERTY_TAX, 'Property Tax'],
  [Category.PROVIDENT_FUND, 'Provident Fund'],
  [Category.RESTAURANT, 'Restaurant'],
  [Category.RESTAURANT_TAKEAWAY, 'Takeaway Restaurant'],
  [Category.SALARY, 'Salary'],
  [Category.SCOOTER, 'Scooter'],
  [Category.SUPERMARKET, 'Supermarket'],
  [Category.SPORT_MEMBERSHIP, 'Sport Membership'],
  [Category.SPORT_TICKET, 'Sport Ticket'],
  [Category.TELEVISION_BILL, 'Television Bill'],
  [Category.TRANSPORTATION, 'Transportation'],
  [Category.VACATION_IN_HOUSE, 'Vacation in House'],
  [Category.VACATION_ON_BOARD, 'Vacation On Board'],
  [Category.WATER_BILL, 'Water Bill'],
]);

export const transactionsTypeTitleMapping = new Map<Type, string>([
  [Type.INCOME, 'Income'],
  [Type.EXPENSE, 'Expense'],
]);
